trigger:
- main
 
pool:
  name: 'nikhil'
 
steps:
- script: |
    cd Backend
    source BEvenv/bin/activate
    python3 app.py
  displayName: 'Build and run app.py'
 
- script: | 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'