
trigger:
- main
 
pool:
  name: 'nikhil'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
- script: |
    python -m pip install Flask
    python -m compileall Backend
  displayName: 'Build and run app.py'
 
- script: | 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'